M48
; DRILL file {KiCad (6.0.11)} date Fri Jan 26 14:49:33 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-26T14:49:33-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X0.5551Y1.2448
X0.5551Y0.1306
X1.7795Y1.2448
T0
M30
